// Generated by CoffeeScript 1.7.1
(function() {
  var PixUsers;

  PixUsers = (function() {
    function PixUsers() {}

    PixUsers.prototype.getAccount = function(callback, optionData) {
      var args, data;
      if (!pixnet.isLogin) {
        pixnet._error('Need login');
        return this;
      }
      data = {
        access_token: pixnet.getData('accessToken')
      };
      data = pixnet._extends(data, optionData);
      args = arguments;
      pixnet._get('https://emma.pixnet.cc/account', {
        data: data,
        done: (function(_this) {
          return function(data) {
            if (callback) {
              return callback(JSON.parse(data));
            }
          };
        })(this),
        fail: (function(_this) {
          return function(data) {
            return pixnet.apiInvalidGrantFunc(function() {
              return _this.getAccount.apply(_this, args);
            }, data);
          };
        })(this)
      });
      return this;
    };

    PixUsers.prototype.getUser = function(callback, userName, optionData) {
      var data;
      data = {};
      data = pixnet._extends(data, optionData);
      pixnet._get("https://emma.pixnet.cc/users/" + userName, pixnet._defaultXHROptions(data, callback));
      return this;
    };

    return PixUsers;

  })();

  pixnet.users = new PixUsers();

}).call(this);
