// Generated by CoffeeScript 1.7.1
(function() {
  var PixUsers;

  PixUsers = (function() {
    function PixUsers() {}

    PixUsers.prototype.getMyAccount = function(opts) {
      var data, done;
      if (pixnet.isLogin) {
        done = opts.done || function() {};
        data = pixnet.getData();
        return pixnet._get('https://emma.pixnet.cc/account', {
          data: {
            access_token: data.app.accessToken
          },
          done: (function(_this) {
            return function(data) {
              return done(JSON.parse(data));
            };
          })(this)
        });
      } else {
        return this._log('Need login');
      }
    };

    return PixUsers;

  })();

  pixnet.users = new PixUsers();

}).call(this);
