// Generated by CoffeeScript 1.7.1
(function() {
  var Container, NoJquery, PixApi, PixConsole, SuperClass, moduleKeywords,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  moduleKeywords = ['included', 'extended'];

  SuperClass = (function() {
    function SuperClass() {}

    SuperClass.include = function(obj) {
      var included, key, value, _ref;
      if (!obj) {
        throw 'include(obj) requires obj';
      }
      _ref = obj.prototype;
      for (key in _ref) {
        value = _ref[key];
        if (__indexOf.call(moduleKeywords, key) < 0) {
          this.prototype[key] = value;
        }
      }
      included = obj.included;
      if (included) {
        included.apply(this);
      }
      return this;
    };

    return SuperClass;

  })();


  /*
   */

  NoJquery = (function() {
    function NoJquery() {
      this._ajax = __bind(this._ajax, this);
      this._get = __bind(this._get, this);
      this._getUrlPara = __bind(this._getUrlPara, this);
      this._serialize = __bind(this._serialize, this);
    }

    NoJquery.prototype._hasProp = {}.hasOwnProperty;

    NoJquery.prototype._extends = function(child, parent) {
      var key;
      for (key in parent) {
        if (!__hasProp.call(parent, key)) continue;
        child[key] = parent[key];
      }
      return child;
    };

    NoJquery.prototype._serialize = function(data) {
      var dataString, key, val;
      dataString = '';
      if (typeof data === 'object') {
        for (key in data) {
          val = data[key];
          if (dataString === '') {
            dataString += "?" + key + "=" + val;
          } else {
            dataString += "&" + key + "=" + val;
          }
        }
        return dataString;
      } else {
        return dataString;
      }
    };

    NoJquery.prototype._getUrlPara = function(name) {
      var item, para, params, url, _i, _len;
      url = window.location.search;
      if (-1 !== url.indexOf("?")) {
        params = url.split("?")[1].split("&");
        for (_i = 0, _len = params.length; _i < _len; _i++) {
          item = params[_i];
          para = item.split("=");
          if (para[0] === name) {
            return para[1];
          } else {
            return void 0;
          }
        }
      } else {
        return void 0;
      }
    };

    NoJquery.prototype._ajaxOpts = {
      type: 'GET',
      url: '',
      data: {},
      dataType: 'text',
      charset: 'UTF-8',
      enctype: 'application/x-www-form-urlencoded'
    };

    NoJquery.prototype._get = function(url, opts) {
      opts.url = url;
      return this._ajax(opts);
    };

    NoJquery.prototype._ajax = function(opts) {
      var done, fail, params, request;
      opts = this._extends(this._ajaxOpts, opts);
      switch (opts.type) {
        case 'GET':
          opts.url += this._serialize(opts.data);
          params = "";
          break;
        default:
          params = JSON.stringify(opts.data);
      }
      done = opts.done || opts.success || function() {};
      fail = opts.fail || opts.error || function() {};
      request = new XMLHttpRequest();
      request.open(opts.type, opts.url, true);
      request.setRequestHeader('Content-Type', "" + opts.enctype + "; charset=" + opts.charset);
      request.onload = function() {
        var resp;
        if (request.status >= 200 && request.status < 400) {
          resp = request.responseText;
          if (opts.dataType === 'json') {
            resp = JSON.parse(resp);
          }
          if (typeof done === 'function') {
            return done(resp);
          }
        } else {
          resp = request.responseText;
          if (typeof fail === 'function') {
            return fail(resp);
          }
        }
      };
      request.send(params);
      return request;
    };

    return NoJquery;

  })();

  PixConsole = (function() {
    function PixConsole() {}

    PixConsole.prototype._log = function(msg) {
      return console.log("PixApi Log:", msg);
    };

    PixConsole.prototype._error = function(msg) {
      return console.error("PixApi Error", msg);
    };

    return PixConsole;

  })();

  Container = (function(_super) {
    __extends(Container, _super);

    function Container() {
      return Container.__super__.constructor.apply(this, arguments);
    }

    Container.include(PixConsole);

    Container.include(NoJquery);

    return Container;

  })(SuperClass);

  PixApi = (function(_super) {
    __extends(PixApi, _super);

    function PixApi() {
      this.getTokens = __bind(this.getTokens, this);
      this.login = __bind(this.login, this);
      this.setCode = __bind(this.setCode, this);
      this.setKey = __bind(this.setKey, this);
      this.setSceret = __bind(this.setSceret, this);
      this.getData = __bind(this.getData, this);
      return PixApi.__super__.constructor.apply(this, arguments);
    }

    PixApi.prototype.data = {
      app: {
        code: '',
        consumerKey: '',
        consumerSceret: '',
        callbackUrl: '',
        isLogin: false,
        loginOpts: {
          type: 'onepage',
          popwin: void 0
        }
      }
    };

    PixApi.prototype.getData = function() {
      return this.data;
    };

    PixApi.prototype.setSceret = function(sceret) {
      this.data.app.consumerSceret = sceret;
      return this;
    };

    PixApi.prototype.setKey = function(key) {
      this.data.app.consumerKey = key;
      return this;
    };

    PixApi.prototype.setCode = function(code) {
      this.data.app.code = code;
      return this;
    };

    PixApi.prototype.init = function(options) {
      if (options.consumerKey) {
        this.data.app.consumerKey = options.consumerKey;
      }
      if (options.consumerSecret) {
        this.data.app.consumerSecret = options.consumerSecret;
      }
      if (options.callbackUrl) {
        this.data.app.callbackUrl = options.callbackUrl;
      }
      if (options.login === true) {
        this.login(this.data.app.loginOpts);
      }
      return this;
    };

    PixApi.prototype.login = function(opts) {
      var callbackUrl, consumerKey, url;
      opts = this._extends(this.data.app.loginOpts, opts);
      callbackUrl = opts.callbackUrl || this.data.app.callbackUrl;
      consumerKey = this.data.app.consumerKey;
      if (!callbackUrl) {
        this._error('callbackUrl is not defined');
      }
      if (!consumerKey) {
        this._error('consumerKey is not defined');
      }
      if (this._getUrlPara('code') && opts.type !== 'custom') {
        this.data.app.code = this._getUrlPara('code');
        this.data.app.isLogin = true;
        if (opts.onGetCode) {
          opts.onGetCode.call(this, this.data.app.code);
        }
        this.getTokens(opts);
      } else {
        url = "https://emma.pixnet.cc/oauth2/authorize?redirect_uri=" + callbackUrl + "&client_id=" + consumerKey + "&response_type=code";
        switch (opts.type) {
          case 'custom':
            if (!opts.custom) {
              this._error('You must set a custom function for getting code from oauth2');
            }
            opts.custom.apply(this, arguments);
            break;
          case 'popwin':
            this.data.app.loginOpts.popwin = window.open(url, 'getCodeWindow');
            break;
          default:
            location.href = url;
        }
      }
      return this;
    };

    PixApi.prototype.getTokens = function(opts) {
      var data, done, fail;
      data = this._extends(this.data.app, opts.data);
      if (!data.consumerSecret) {
        this._error('consumerSecret is not defined');
      }
      done = opts.onGetTokens || function() {};
      fail = opts.fail || function() {};
      return this._get('https://emma.pixnet.cc/oauth2/grant', {
        data: {
          redirect_uri: data.callbackUrl,
          client_id: data.consumerKey,
          client_secret: data.consumerSecret,
          code: data.code,
          grant_type: "authorization_code"
        },
        done: done,
        fail: fail
      });
    };

    return PixApi;

  })(Container);

  window.PixApi = new PixApi();

}).call(this);
