// Generated by CoffeeScript 1.7.1
(function() {
  var PixBlog;

  PixBlog = (function() {
    function PixBlog() {}

    PixBlog.prototype.a = function() {
      return console.log(555);
    };

    return PixBlog;

  })();

  pixnet.blog = new PixBlog();

}).call(this);
