// Generated by CoffeeScript 1.7.1
(function() {
  var PixAlbum;

  PixAlbum = (function() {
    function PixAlbum() {}

    PixAlbum.prototype.a = function() {
      return console.log(555);
    };

    return PixAlbum;

  })();

  PixApi.Album = new PixAlbum();

}).call(this);
